config/routes.rb
Rails.application.routes.draw do

  resources :hooks
   get '/', to: "users#index", as: 'welcome' 
 #  resources :character_junks
 #  resources :junks
   resources :character_jobs, only: [:create]
   resources :characters, only: [:show, :new, :create, :destroy, :update]
   resources :jobs
   resources :users, only: [:index, :new, :create, :show]
   resources :login, only: [:new, :create]
   delete "logout", to: "login#destroy", as: "log_out"
  

   # resources :jobs, only: [:index] do 
   #    resources :characters, only: [:create]
   #  end

   

   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
    has_many :character_jobs
    # has_many :character_junks
    has_many :jobs, through: :character_jobs
    # has_many :junks, through: :character_junks
    has_many :hooks, through: :jobs
    belongs_to :user
end

app/models/character_job.rb
class CharacterJob < ApplicationRecord
    belongs_to :job
    belongs_to :character
end

app/models/character_junk.rb
class CharacterJunk < ApplicationRecord
    belongs_to :character
    belongs_to :junk
end

app/models/hook.rb
class Hook < ApplicationRecord
    belongs_to :job, optional: true
    serialize :result, Hash
end

app/models/job.rb
class Job < ApplicationRecord
    has_many :character_jobs
    has_many :characters, through: :character_jobs
    has_many :children, class_name: "Job", foreign_key: "parent_id"
    belongs_to :parent, class_name: "Job", optional: true
    has_many :hooks
end

app/models/junk.rb
class Junk < ApplicationRecord
    has_many :character_junks
    has_many :characters, through: :character_junks
end

app/models/user.rb
class User < ApplicationRecord
  has_many :characters

  validates_presence_of :username
  validates_uniqueness_of :username

 
  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
      before_action :auths
      before_action :authenticate!
    

      private
    
      def auths
        @logged_in_user_id = session[:user_id]
        @logged_in = !!@logged_in_user_id
    
        @notification = flash[:notification]
        @errors = flash[:errors]
        
        if @logged_in
          @logged_in_user = User.find(@logged_in_user_id) 
         
        end
      end
    
      def authenticate!
        unless @logged_in
          flash[:errors] = [ "Log in first!" ]
          redirect_to new_login_path
        end
      end
    
      def authorized?(user_id)
        user_id == @logged_in_user_id
      end
    
    end
   

app/controllers/characters_controller.rb
class CharactersController < ApplicationController


    def show
        @character = Character.find(params[:id])
        @jobs = @character.jobs
        @character_hooks = @jobs.map{|job| job.hooks}.flatten
    end

    def new
        @character = Character.new  
    end

    def create
        @character = Character.create(name: params[:character][:name], user_id: @logged_in_user_id)
        CharacterJob.create(character_id: @character.id, job_id: Job.first.id)
        redirect_to @character
    end

    def update
        @character = Character.find(params[:id])
        flash[:notification] = Hook.find(params[:character][:hook_ids]).description
        if !CharacterJob.find_by(character_id: @character.id, job_id: Hook.find(params[:character][:hook_ids]).result[:newjob].id)
            CharacterJob.create(character_id: @character.id, job_id: Hook.find(params[:character][:hook_ids]).result[:newjob].id)
        end
        redirect_to character_path(@character)
    end


end

app/controllers/hooks_controller.rb
class HooksController < ApplicationController
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
end

app/controllers/junks_controller.rb
class JunksController < ApplicationController
end

app/controllers/login_controller.rb
class LoginController < ApplicationController

    skip_before_action :authenticate!
  
    def new
    end
  
    def create
      user = User.find_by(username: params[:username])
      if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to user
      else
        flash[:errors] = ["Username or password did not match"]
        redirect_to new_login_path
      end
    end
  
    def destroy
      
      session[:user_id] = nil
      flash[:notification] = "We'll be seeing you again"
      redirect_to new_login_path
    end
  
  
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    skip_before_action :authenticate!
    def index
    end
    
    def new
      @user = User.new
    end
  
    def create
      @user = User.create(user_params)
      if @user.valid?
        redirect_to @user
      else
        flash[:errors] = @user.errors.full_messages
        redirect_to new_user_path
      end
    end

    def show
      @user = User.find(params[:id])
    end
  
    private
  
    def user_params
      params.require(:user).permit(:username, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/character_jobs_helper.rb
module CharacterJobsHelper
end

app/helpers/character_junks_helper.rb
module CharacterJunksHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/hooks_helper.rb
module HooksHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/junks_helper.rb
module JunksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/characters/new.html.erb
<style>
  body { background-image: url(<%= asset_path 'img_0518.jpg' %>);
         height: 100%;
         background-position: center;
         background-repeat: no-repeat;
         background-size: cover;
       }
  ul { padding-right: 20px;
       padding-left: 20px;
     }
  li { list-style-position: inside;
       text-align: center;
       padding-left: 20px;
     }

</style>
<h2>Creating a new character<h2>

<%= form_with model: @character do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name %><br/>
        <%= f.hidden_field @character.jobs, :value => Job.find(1) %>
    <%= f.submit "Begin!" %>
  <% end %>

app/views/characters/show.html.erb
<body>
<h1> <%= @character.name %> </h1>

<br>

</style>

<h1> <%= @character.name %> </h1>
<h3>Classes </h3>
<ul>
<% @jobs[1..-1].each do |job| %>
   <li>
      <%= job.name %>
   </li>
<% end %>
</ul>
        
<h3><%= form_for @character do |f| %>
    <%= collection_select(:character, :hook_ids, @character_hooks, :id, :prompt, {:prompt => 'What would you like to do?'}) %>
    <%= f.submit 'Go!' %>
<% end %>

</body>

app/views/users/index.html.erb
<h1>Adventurers Welcome</h1>
<h2>This is the gritty MiniRpg Game</h2>

<p align="center"><%= image_tag "chris-scalf-unspecified.jpg" %></p>

<h3>Game developed by : Mavi & Pano</h3>

app/views/users/new.html.erb
<style>
  body { background-image: url(<%= asset_path 'bg-heroes_0.jpg' %>);
         height: 100%;
         background-position: center;
         background-repeat: no-repeat;
         background-size: cover;
       }
</style>
<h1>Welcome New MiniRpg User</h1>
<%= form_for @user, html: { class: "auth-form" } do |f| %>
  <ul>
    <li>
      <%= f.label :username %>
      <%= f.text_field :username %>
    </li>
    <li>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </li>
  </ul>
  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<style>
  body { background-image: url(<%= asset_path 'img_0518.jpg' %>);
         height: 100%;
         background-position: center;
         background-repeat: no-repeat;
         background-size: cover;
       }

</style>
<h1> <%= @user.username %>'s past characters: </h1>

<ul class= "characters">
      <% @user.characters.each do |character| %>
      <li class="character" style="background-color: #282828;">
      <%= link_to character.name, character %>
      <p>Classes: </p>
      <ul>
         <li>
            <% character.jobs[1..-1].each do |job| %>
            <p><%= job.name %></p>
        </li>
            <% end %>
        <br>
        </li>
        </ul>
    <br>
  <% end %>
</ul>


<h2><%= link_to "Create A New Character", new_character_path%></h2>