config/routes.rb
Rails.application.routes.draw do

  resources :hooks
   get '/', to: "users#index", as: 'welcome' 
 #  resources :character_junks
 #  resources :junks
   resources :character_jobs, only: [:create]
   resources :characters, only: [:show, :new, :create, :destroy, :update]
   resources :jobs
   resources :users, only: [:index, :new, :create, :show]
   resources :login, only: [:new, :create]
   delete "logout", to: "login#destroy", as: "log_out"
  

   # resources :jobs, only: [:index] do 
   #    resources :characters, only: [:create]
   #  end

   

   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
    has_many :character_jobs
    # has_many :character_junks
    has_many :jobs, through: :character_jobs
    # has_many :junks, through: :character_junks
    has_many :hooks, through: :jobs
    belongs_to :user
end

app/models/character_job.rb
class CharacterJob < ApplicationRecord
    belongs_to :job
    belongs_to :character
end

app/models/character_junk.rb
class CharacterJunk < ApplicationRecord
    belongs_to :character
    belongs_to :junk
end

app/models/hook.rb
class Hook < ApplicationRecord
    belongs_to :job, optional: true
    serialize :result, Hash
end

app/models/job.rb
class Job < ApplicationRecord
    has_many :character_jobs
    has_many :characters, through: :character_jobs
    has_many :children, class_name: "Job", foreign_key: "parent_id"
    belongs_to :parent, class_name: "Job", optional: true
    has_many :hooks
end

app/models/junk.rb
class Junk < ApplicationRecord
    has_many :character_junks
    has_many :characters, through: :character_junks
end

app/models/user.rb
class User < ApplicationRecord
  has_many :characters

  validates_presence_of :username
  validates_uniqueness_of :username

 
  has_secure_password

end

app/controllers/hooks_controller.rb
class HooksController < ApplicationController
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
end

app/controllers/junks_controller.rb
class JunksController < ApplicationController
end

app/controllers/login_controller.rb
class LoginController < ApplicationController

    skip_before_action :authenticate!
  
    def new
    end
  
    def create
      user = User.find_by(username: params[:username])
      if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to user
      else
        flash[:errors] = ["Username or password did not match"]
        redirect_to new_login_path
      end
    end
  
    def destroy
      
      session[:user_id] = nil
      flash[:notification] = "We'll be seeing you again"
      redirect_to new_login_path
    end
  
  
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    skip_before_action :authenticate!
    def index
    end
    
    def new
      @user = User.new
    end
  
    def create
      @user = User.create(user_params)
      if @user.valid?
        redirect_to @user
      else
        flash[:errors] = @user.errors.full_messages
        redirect_to new_user_path
      end
    end

    def show
      @user = User.find(params[:id])
    end
  
    private
  
    def user_params
      params.require(:user).permit(:username, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/character_jobs_helper.rb
module CharacterJobsHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/hooks_helper.rb
module HooksHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/junks_helper.rb
module JunksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minirpg</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <h4>
      <% if @logged_in %>
        Welcome, young <%= @logged_in_user.username.titleize %>...
        <%= button_to "Log out", log_out_path, method: :delete %>
  <%#<!--You have <%= @logged_in_user.# -  characters -->%>
      <% else %>
        <%= link_to "Log in", new_login_path %>
        <%= link_to "Sign up", new_user_path %>
      <% end %>

      <% if @notification %> 
        <p class="message">
          <%= @notification.html_safe %>
      
        </p>
      <% end %>

      <% if @errors && @errors.any? %>
      <ul class="errors">
        <% @errors.each do |error| %>
        <li>
          <%= error %>
          
        </li>
        <% end %>
      </ul>
      <% end %>

    </h4>

    <%= yield %>

  </body>
</html>